M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Tue 25 Jun 2024 15:30:45 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-25T15:30:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X36.5Y-69.615
X42.28Y-69.615
T2
X30.24Y-33.95
X30.24Y-73.66
X105.02Y-33.95
X105.02Y-73.66
M30
